### ISSUE TITLE
vercel builds failing

### ISSUE THREAD

**Issue by begna112** [GrygrFlzr/are-we-there-yet#14]
This is the latest error.
```
37 packages are looking for funding
  run `npm fund` for details
> are-we-there-yet@2.0.0 build:vercel /vercel/path0
> svelte-kit build
warn - 'coolGray' has been renamed to 'gray'.
warn - Please update your color palette to eliminate this warning.
> config.kit.target is no longer required, and should be removed
    at file:///vercel/path0/node_modules/@sveltejs/kit/dist/cli.js:877:10
    at file:///vercel/path0/node_modules/@sveltejs/kit/dist/cli.js:769:43
    at file:///vercel/path0/node_modules/@sveltejs/kit/dist/cli.js:755:18
    at file:///vercel/path0/node_modules/@sveltejs/kit/dist/cli.js:755:18
    at validate_config (file:///vercel/path0/node_modules/@sveltejs/kit/dist/cli.js:939:9)
    at load_config (file:///vercel/path0/node_modules/@sveltejs/kit/dist/cli.js:916:20)
    at async file:///vercel/path0/node_modules/@sveltejs/kit/dist/cli.js:1051:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! are-we-there-yet@2.0.0 build:vercel: `svelte-kit build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the are-we-there-yet@2.0.0 build:vercel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /vercel/.npm/_logs/2022-02-27T21_47_58_749Z-debug.log
```

**Comment by begna112** [comment]
after manually fixing the above, the following errors present:

```
Error: request in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details
--
15:48:44.546 | at Object.get request [as request] (file:///vercel/path0/.svelte-kit/output/server/index.js:1892:15)
15:48:44.546 | at Object.handle (file:///vercel/path0/.svelte-kit/output/server/index.js:1929:25)
15:48:44.546 | at respond (file:///vercel/path0/.svelte-kit/output/server/index.js:1769:42)
15:48:44.546 | at Server.respond (file:///vercel/path0/.svelte-kit/output/server/index.js:1995:12)
15:48:44.546 | at visit (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:1076:33)
15:48:44.546 | at Object.fn (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:1059:22)
15:48:44.546 | at dequeue (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:645:42)
15:48:44.546 | at Object.add (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:672:4)
15:48:44.546 | at enqueue (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:1059:12)
15:48:44.546 | at prerender (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:1202:6)
15:48:44.554 | Error: request in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details
15:48:44.554 | at Object.get request [as request] (file:///vercel/path0/.svelte-kit/output/server/index.js:1892:15)
15:48:44.554 | at Object.handle (file:///vercel/path0/.svelte-kit/output/server/index.js:1929:25)
15:48:44.554 | at respond (file:///vercel/path0/.svelte-kit/output/server/index.js:1769:42)
15:48:44.555 | at Server.respond (file:///vercel/path0/.svelte-kit/output/server/index.js:1995:12)
15:48:44.555 | at visit (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:1076:33)
15:48:44.555 | at Object.fn (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:1059:22)
15:48:44.555 | at dequeue (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:645:42)
15:48:44.555 | at file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:654:7
15:48:44.555 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
15:48:44.555 | > 500 /
15:48:44.555 | at file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:975:11
15:48:44.555 | at save (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:1194:4)
15:48:44.556 | at visit (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:1085:3)
15:48:44.556 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
15:48:44.569 | npm ERR! code ELIFECYCLE
15:48:44.570 | npm ERR! errno 1
15:48:44.572 | npm ERR! are-we-there-yet@2.0.0 build:vercel: `svelte-kit build`
15:48:44.573 | npm ERR! Exit status 1
15:48:44.573 | npm ERR!
15:48:44.573 | npm ERR! Failed at the are-we-there-yet@2.0.0 build:vercel script.
15:48:44.573 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
15:48:44.580 |  
15:48:44.580 | npm ERR! A complete log of this run can be found in:
15:48:44.580 | npm ERR!     /vercel/.npm/_logs/2022-03-06T21_48_44_573Z-debug.log
15:48:44.590 | Error: Command "npm run build:vercel" exited with 1
```

I haven't been able to figure out how to resolve this one.
