### ISSUE TITLE
Cannot read property 'flatMap' of undefined

### ISSUE THREAD

**Issue by fmohican** [GrygrFlzr/are-we-there-yet#5]
```
[root@cOS-82.64]# npx svelte-kit start -p 3001
> Listening on http://localhost:3001
TypeError: Cannot read property 'flatMap' of undefined
    at allGroupPositions (file:///root/are-we-there-yet/.svelte/build/unoptimized/server/_components/utils.js:41:22)
    at groupCorePositions (file:///root/are-we-there-yet/.svelte/build/unoptimized/server/_components/utils.js:73:21)
    at Object.prepare (file:///root/are-we-there-yet/.svelte/build/unoptimized/server/_app/setup/index.js:10:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at render (file:///root/are-we-there-yet/node_modules/@sveltejs/kit/src/renderer/index.js:22:4)
    at file:///root/are-we-there-yet/node_modules/@sveltejs/kit/src/api/start/index.js:33:23
```

```
[root@cOS-82.64]# node -v
v14.9.0
[root@cOS-82.64]# npm -v
7.5.4
```

The page `/config` its work fine, but the main page `/` isn't and also the `/?theme=light&accent=green&size=normal&lang=en` isnt.
On the page it says
"Connection error
Internal server error, contact site operators"

**Comment by GrygrFlzr** [comment]
Sorry about that, I documented the wrong steps. That said, there's a bug from upstream preventing the use of the node adapter.

Is there a particular reason you don't want to use vercel / netlify?

**Comment by fmohican** [comment]
No in particular, but i dislike to use other services a-like, that's why I bought a server and pay D.C. rent.

**Comment by GrygrFlzr** [comment]
Okay, since the node adapter is out of commission for now, you can use this workaround:

```bash
npm run start -- --port 4000
```

Which would start it at port 4000.

I'll leave the issue open until the proper adapter works.
